Vision p6 int8 pad
tensorflow/tflite-micro pull request #1138
Opened 2022-05-17 14:12 UTC by psharath1

BUG= Support for INT8 Pad on VisionP6

2022-05-17 17:20 UTC, rascani requested changes

2022-05-17 17:33 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/pad_vision.cc
> +  if (!status && context_size) {
should we add something like TFLITE_DCHECK(&context_size != nullptr)? it is actually redundant as the value is on stack.
let us know if this needs to be changed

2022-05-17 23:58 UTC, trinitylundgren approved these changes

2022-06-02 22:49 UTC, tingyan19 commented on tensorflow/lite/micro/kernels/xtensa/pad_vision.cc
> +  if (!status && context_size) {
Just updated the code according to recommendation from @rascani

2022-06-02 23:15 UTC, rascani approved these changes

2022-06-02 23:46 UTC, tingyan19 approved these changes

2022-06-02 23:47 UTC, merged