Integrate the HiFi 5 Neural Network Library v1.5.0
tensorflow/tflite-micro pull request #115
Opened 2021-06-02 18:54 UTC by bhanuprakashbv

Integrated HiFi 5 NN Library kernels for below operators
  svdf(int8),
  quantize(int8),
  add(int8, uint8 and float32),
  mul(int8, uint8 and float32),
  relu(int8, uint8 and float32) and
  relu6(int8, uint8 and float32)

Signed-off-by: Anirban Mandal <amandal@cadence.com>
Signed-off-by: Biswa Dhal <bdhal@cadence.com>
Signed-off-by: Bhanu Prakash Bandaru Venkata <bhanup@cadence.com>
Signed-off-by: Chaitanya Sanjay Muley <cmuley@cadence.com>
Signed-off-by: Harinarayanan E V <hariev@cadence.com>
Signed-off-by: Harshavardhan Ravindra Joshi <joshih@cadence.com>

2021-06-02 23:16 UTC, advaitjain requested changes
For mul, add and activations we will need to first refactor the reference kernels so that the code that is shared between the reference and optimized implementations is reused -- let's tackle these ops in separate PRs.

2021-06-02 23:16 UTC, advaitjain commented on tensorflow/lite/micro/kernels/xtensa/quantize.cc
> +******************************************************************************/
Similar to the other already merged Xtensa kernels, we will need to remove this copyright. The only permissible copyright is for the Tensorflow Authors.

2021-06-02 23:16 UTC, advaitjain commented on tensorflow/lite/micro/kernels/xtensa/svdf.cc
> +******************************************************************************/
remove

2021-06-02 23:16 UTC, advaitjain commented on tensorflow/lite/micro/kernels/xtensa/xtensa.h
> + ******************************************************************************/
remove

2021-06-02 23:16 UTC, advaitjain commented on tensorflow/lite/micro/kernels/xtensa/xtensa.h
> +  }
let's directly use the tflite macros (TF_LITE_EXPECT_EQ(context, ..., 0);

2021-06-03 06:54 UTC, bhanuprakashbv commented
@advaitjain, updated the code based on your review comments (commit id:725775df1d10713e91d356cdf470a18d50e2d40a).
Currently removed add.cc, mul.cc and activations.cc from this PR. Let me know when can I integrate for these operators.

2021-06-03 17:27 UTC, advaitjain approved these changes

2021-06-03 17:40 UTC, merged