Vision p6 add
tensorflow/tflite-micro pull request #1180
Opened 2022-06-03 16:23 UTC by psharath1

BUG= Added support for ADD operator on Vision P6

2022-06-03 22:10 UTC, rascani requested changes
LGTM. Just a couple nits on the new file license year.

2022-06-03 22:10 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/xtensa_add.h
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022

2022-06-03 22:10 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/add_vision.cc
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022

2022-06-06 06:53 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/xtensa_add.h
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
updated

2022-06-06 06:53 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/add_vision.cc
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
updated

2022-06-06 16:28 UTC, rascani submitted a review, later dismissed

2022-06-06 20:13 UTC, tingyan19 submitted a review, later dismissed

2022-06-06 22:29 UTC, tingyan19 approved these changes

2022-06-06 22:53 UTC, merged