Vision p6 pooling
tensorflow/tflite-micro pull request #1181
Opened 2022-06-03 16:59 UTC by psharath1

BUG= Added support for pooling on Vision P6

2022-06-03 22:17 UTC, rascani requested changes
Overall LGTM

2022-06-03 22:17 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/xtensa_pooling.h
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022

2022-06-03 22:17 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +  return (PoolingPrepareVision(context, node, AVG_POOLING));
Can drop the outer parens.

2022-06-03 22:17 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +  return (PoolingPrepareVision(context, node, MAX_POOLING));
Can drop the outer parens here too.

2022-06-03 22:17 UTC, rascani commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022

2022-06-06 06:50 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/xtensa_pooling.h
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
Updated

2022-06-06 06:50 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +  return (PoolingPrepareVision(context, node, AVG_POOLING));
updated

2022-06-06 06:50 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +  return (PoolingPrepareVision(context, node, MAX_POOLING));
updated

2022-06-06 06:50 UTC, psharath1 commented on tensorflow/lite/micro/kernels/xtensa/pooling_vision.cc
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
Updated

2022-06-06 16:19 UTC, tingyan19 submitted a review, later dismissed

2022-06-06 16:30 UTC, rascani submitted a review, later dismissed

2022-06-06 21:22 UTC, tingyan19 approved these changes

2022-06-06 22:04 UTC, merged