Added SQUARED_DIFFERENCE to ops resolver
tensorflow/tflite-micro pull request #1246
Opened 2022-07-07 15:38 UTC by mikljohansson

Add support for the SQUARED_DIFFERENCE op in the ops resolvers

BUG=b/238912370

2022-07-07 15:41 UTC, mikljohansson commented
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/tensorflow/tflite-micro/pull/1246/checks?check_run_id=7236766364) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

I've now signed the CLA and this check now passes

2022-07-13 19:29 UTC, paulinesho commented on tensorflow/lite/core/api/flatbuffer_conversions.cc
> +TfLiteStatus ParseSquaredDifference(const Operator*, ErrorReporter*, BuiltinDataAllocator*,
Thanks for adding this change! It looks good to me and we do want all the changes here. However, `flatbuffer_conversions.cc/h` are files that we pull from TFLite, so those changes will have to go into TFLite first. The process is a little involved, and currently the TFLite->TFLM sync is broken, so we will handle the changes in these two files here. We'll revisit this PR after the sync is completed, which means this PR should then only contain changes in the `micro` folder.

2022-07-28 15:41 UTC, paulinesho requested changes

2022-07-28 15:41 UTC, paulinesho commented on tensorflow/lite/core/api/flatbuffer_conversions.cc
> +TfLiteStatus ParseSquaredDifference(const Operator*, ErrorReporter*, BuiltinDataAllocator*,
@mikljohansson The changes in `flatbuffer_conversions.cc/h` have been sync'd to the TFLM repo, please remove the changes here and we can proceed to merge this PR.

2022-07-28 15:44 UTC, paulinesho approved these changes

2022-08-01 15:19 UTC, paulinesho submitted a review, later dismissed

2022-08-05 19:20 UTC, paulinesho approved these changes

2022-08-05 22:23 UTC, merged