CMSIS-NN: add int16 support for int16 elementwise MUL
tensorflow/tflite-micro pull request #1535
Opened 2022-11-08 08:04 UTC by annietllnd

We have updated the call for quantized int16 to reflect the recently added MVE support

BUG=#1534

2022-11-09 09:05 UTC, advaitjain approved these changes

2022-11-09 09:13 UTC, advaitjain requested changes
We should also add int16 support to the reference kernels and unit tests as well. We want to avoid a state where optimized kernels have a superset of functionality relative to the reference kernels.

2022-11-29 07:44 UTC, annietllnd commented on tensorflow/lite/micro/kernels/cmsis_nn/mul.cc
>          tflite::micro::GetTensorShape(output),
Nice catch, done

2022-11-30 08:16 UTC, mansnils approved these changes

2022-11-30 09:28 UTC, advaitjain commented
Let's wait for https://github.com/tensorflow/tflite-micro/pull/1592 to be merged and then we will have at least basic unit test coverage, and can merge this PR as well.

2022-12-20 17:12 UTC, advaitjain approved these changes

2022-12-20 19:42 UTC, merged