Separate core, kernel and third party objects.
tensorflow/tflite-micro pull request #163
Opened 2021-06-11 04:31 UTC by njeffrie

Add a second optimization level in the Makefile to enable different
levels between kernels and the rest of the TFLM code. This results in a
smaller binary with minimal performance impact compared with using a
single optimization level.

Allows the use of implicit patterns to compile all sources, choosing
different flags for core, kernel and third party sources.

The following measurements are taken using the hexagon toolchain +
hexagon-size and hexagon-sim.

For the keyword benchmark using -O2:
   text    data     bss     dec
  58140   37639   46612  142391

  Cycles: 1700364

For the keyword benchmark using -O2 for kernels and -Oz for framework:
   text    data     bss     dec
  52796   37623   46612  137031

  Cycles: 1759664

2021-06-11 21:14 UTC, advaitjain requested changes
small nits only

2021-06-11 21:14 UTC, advaitjain commented on tensorflow/lite/micro/tools/make/Makefile
> +BASE_OPTIMIZATION_LEVEL := -Os
call this CORE_OPTIMIZATION_LEVEL? to match the CORE_OBJDIR?

2021-06-11 21:53 UTC, njeffrie commented on tensorflow/lite/micro/tools/make/Makefile
>  # For normal manually-created TensorFlow C source files.
Done.

2021-06-11 21:53 UTC, njeffrie commented on tensorflow/lite/micro/tools/make/Makefile
>  # For normal manually-created TensorFlow C++ source files.
Done.

2021-06-15 18:18 UTC, advaitjain commented
closing in favor of https://github.com/tensorflow/tflite-micro/pull/168

2021-06-15 18:18 UTC, closed without merging