Port int8 and int16 in ABS kernel to micro
tensorflow/tflite-micro pull request #204
Opened 2021-06-21 14:10 UTC by patriklaurell

@advaitjain this PR ports int8 and int16 support to ABS kernel.

Closes #190

2021-06-22 14:56 UTC, patriklaurell commented
@advaitjain all tests passed. Ready for review

2021-06-25 06:25 UTC, advaitjain requested changes
There is a lot of somewhat subtle code that can be shared between the TFL and TFLM implementation. It appears that other than the Init functions almost everything else can be shared?

I think we should refactor the TFL kernel to move the shared code into tensorflow/lite/kernels/elementwise_portable.cc and elementwise_portable.h

and then use the shared code from micro/kernels/elementwise.cc

The TFL refactoring will have to go in the tensorflow repo.

2021-06-25 06:25 UTC, advaitjain commented on tensorflow/lite/micro/kernels/elementwise.cc
> +  int shift;
nit: int32_t

2021-06-25 06:25 UTC, advaitjain commented on tensorflow/lite/micro/kernels/elementwise.cc
> +inline void SetAbsOutputMultiplier(const float input_scale,
nit: remove inline

2021-06-28 12:00 UTC, patriklaurell commented
@advaitjain That sounds like a good idea. 

So to clarify. I move all the shared code into elementwise_portable.cc and elementwise_portable.h, and submit that as a PR to the tensorflow repo. Once that PR is merged will it automatically be merged into this repo or will I need to create an additional PR to merge the elementwise_portable change into this repo?

2021-07-07 21:33 UTC, advaitjain commented
> @advaitjain That sounds like a good idea.
> 
> So to clarify. I move all the shared code into elementwise_portable.cc and elementwise_portable.h, and submit that as a PR to the tensorflow repo. Once that PR is merged will it automatically be merged into this repo or will I need to create an additional PR to merge the elementwise_portable change into this repo?

Apologies for the delay.

Yes, let's make a PR in the tensorflow repo for the shared code. Once it is merged, explicitly adding the shared code to https://github.com/tensorflow/tflite-micro/blob/a7f2a887bd947c7378d8eada2d0b82dd5a8c1ca9/ci/sync_from_upstream_tf.sh#L34-L36 will allow it to be sync'd to this repo -- I can help with the sync.

2021-07-19 11:34 UTC, patriklaurell commented
@advaitjain I opened [this PR](https://github.com/tensorflow/tensorflow/pull/50836) for the refactoring of the elementwise kernel in TFLite.

I couldn't refactor out the eval code into elementwise_portable.h because Lite uses std::function, whereas the micro code is written in a way to avoid that. If I am not mistaken this is done to avoid dynamic allocation. Should we keep it like this or should I change the lite code to be aligned with the way it is done in micro?

2021-08-18 08:30 UTC, patriklaurell commented
After talking with @advaitjain we decided that the std::function uses in the Lite kernel should be removed and implemented as in Micro, so that more code can be shared between Lite and Micro. I am working on that refactoring now and will push it to [the PR in the main tensorflow repo ](https://github.com/tensorflow/tensorflow/pull/50836)

2022-09-03 04:54 UTC, advaitjain commented
Closing old PR. Let's reopen if needed.

2022-09-03 04:54 UTC, closed without merging