Port int16 support to Mean kernel
tensorflow/tflite-micro pull request #250
Opened 2021-07-06 13:59 UTC by patriklaurell

@advaitjain this PR ports int16 support to the Mean kernel.

Closes #239

2021-07-14 06:16 UTC, patriklaurell commented
@advaitjain ready for review

2021-07-15 23:54 UTC, advaitjain commented
apologies for the delay. I will review and respond tomorrow.

2021-07-16 17:19 UTC, advaitjain requested changes

2021-07-16 17:19 UTC, advaitjain commented on tensorflow/lite/micro/kernels/reduce_test.cc
> +TF_LITE_MICRO_TEST(MeanInt162DKeepDims) {
Am I missing something or is it the case that the test cases are only tesing a single code branch
```cc
      } else if (op_data->input_zp == op_data->output_zp &&
                 op_data->input_scale == op_data->output_scale) {
```

Looks like this is not unique to the int16 port so I'm happy to make a Github issue to come back and fix this for the other types as well.

If you can add in additional test cases for int16 to the current PR, that would be appreciated.

2021-07-22 10:17 UTC, patriklaurell commented
@advaitjain The old tests cover the first two code paths
```cpp
if (params->keep_dims && special_case_4d_axes_1_and_2) {
```
and
```cpp
} else if (op_data->input_zp == op_data->output_zp &&
                 op_data->input_scale == op_data->output_scale) {
```
I added an additional test to cover the else clause.

2021-07-22 23:59 UTC, advaitjain approved these changes

2021-07-23 00:10 UTC, merged