Add int16 support to RELU
tensorflow/tflite-micro pull request #2727
Opened 2024-10-18 13:55 UTC by andresovela

This PR adds int16 support to RELU

bug=#2726

2024-10-19 22:58 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/activations_test.cc
> +  int input_shape[] = {2, 1, 5};
This should be `2, 2, 5`

2024-10-19 22:59 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/activations_test.cc
> +  int output_shape[] = {2, 1, 5};
This should be `2, 2, 5`

2024-10-19 23:09 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/activations_common.cc
In `ReluPrepare` the following code should be used to conform with TfLite (LiteRT):
```
  if (input->type == kTfLiteInt8) {
    CalculateReluOpData<int8_t>(input, output, data);
  }
  else if (input->type == kTfLiteInt16) {
    TF_LITE_ENSURE_EQ(context, input->params.zero_point, 0);
    TF_LITE_ENSURE_EQ(context, output->params.zero_point, 0);
    CalculateReluOpData<int16_t>(input, output, data);
  }
```

I am very surprised (and concerned) that the unit test passed, even though `CalculateReluIOpData<int16_t>` was not being called.

2024-10-19 23:11 UTC, ddavis-2015 commented
Thank you for submitting this PR.  I have flagged the errors in the kernel and unit test above.  On to @suleshahid for approval.

2024-10-21 09:20 UTC, andresovela commented on tensorflow/lite/micro/kernels/activations_test.cc
> +  int input_shape[] = {2, 1, 5};
Done

2024-10-21 09:20 UTC, andresovela commented on tensorflow/lite/micro/kernels/activations_test.cc
> +  int output_shape[] = {2, 1, 5};
Done

2024-12-01 10:33 UTC, andresovela commented
Waiting for approval

2025-01-12 16:24 UTC, andresovela commented
Still waiting for review/approval

2025-03-04 10:54 UTC, ddavis-2015 requested changes
@andresovela Thank you for your interest in TFLM (RTLM) and for submitting this PR!
Also, thank you for your persistence and perseverance.

This change looks good. Please make sure to merge with the latest main branch so there are no conflicts.

Also, another Google procedural requirement: All changed files should have the copyright year set the to current year (I know you submitted this last year). Only the current year should appear in the copyright.

2025-03-04 13:19 UTC, andresovela commented
Done

2025-03-06 04:10 UTC, ddavis-2015 approved these changes
@suleshahid Everything looks good.

2025-03-21 20:55 UTC, suleshahid approved these changes

2025-03-21 21:20 UTC, merged