Add support for CMSIS-NN int8 transpose and padding operators
tensorflow/tflite-micro pull request #2757
Opened 2024-11-08 10:07 UTC by AdrianLundell

BUG=New operator support

2024-11-13 12:12 UTC, mansnils commented
CMSIS-NN SHA is already up to date so cmsis_nn_download.sh script should not be updated. Also AddTranspose in micro_mutable_op_resolver.h should be updated to support quant specific registration.

2024-11-14 10:37 UTC, mansnils approved these changes

2024-11-15 18:53 UTC, suleshahid commented on tensorflow/lite/micro/kernels/transpose_common.cc
> +TfLiteStatus TransposePrepare(TfLiteContext* context, TfLiteNode* node) {
We should remove the duplicate function in transpose.cc and only use this.

2024-11-15 18:53 UTC, suleshahid commented on tensorflow/lite/micro/kernels/transpose.h
> +#include "tensorflow/lite/kernels/internal/reference/transpose.h"
Do we need all these includes? Is there something we duplicate from the internal transpose.h, if so, could we just use it directly from there?

2024-11-18 15:52 UTC, AdrianLundell commented
Thanks for the review, should be all good now

2025-02-05 00:18 UTC, suleshahid commented on tensorflow/lite/micro/kernels/transpose.cc
>  namespace tflite {
sorry for late review, just catching this now. We should remove the common code below and use the one directly from common.

2025-03-04 09:43 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/transpose.cc
>  namespace tflite {
@AdrianLundell I believe @suleshahid is referring to the required removal of the code below in favor of the identical code in the transpose.h file:
```
constexpr int kInputTensor = 0;
constexpr int kPermTensor = 1;
constexpr int kOutputTensor = 0;
struct TransposeContext {
  TransposeContext(TfLiteContext* context, TfLiteNode* node) {
    micro_context = GetMicroContext(context);
    input = micro_context->AllocateTempInputTensor(node, kInputTensor);
    perm = micro_context->AllocateTempInputTensor(node, kPermTensor);
    output = micro_context->AllocateTempOutputTensor(node, kOutputTensor);
  }
  ~TransposeContext() {
    micro_context->DeallocateTempTfLiteTensor(input);
    micro_context->DeallocateTempTfLiteTensor(perm);
    micro_context->DeallocateTempTfLiteTensor(output);
  }
  MicroContext* micro_context;
  TfLiteTensor* input;
  TfLiteTensor* perm;
  TfLiteTensor* output;
};
```

2025-03-19 14:35 UTC, ddavis-2015 requested changes

2025-03-19 14:35 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/transpose.cc
Only the tensor indexing constants from transpose.h should be used in this code.

2025-03-19 14:58 UTC, ddavis-2015 commented on tensorflow/lite/micro/micro_mutable_op_resolver.h
This file didnt actually change, so perhaps it can be removed from the PR?

2025-03-19 15:22 UTC, mansnils commented on tensorflow/lite/micro/micro_mutable_op_resolver.h
Yes good point

2025-03-19 15:30 UTC, ddavis-2015 commented
@AdrianLundell CI code style check does not pass

2025-03-20 14:46 UTC, ddavis-2015 approved these changes
All good here, on to @suleshahid

2025-03-20 22:26 UTC, suleshahid approved these changes

2025-03-20 22:27 UTC, merged