Add 16bit support for unpack, transpose and comparisons operators
tensorflow/tflite-micro pull request #3028
Opened 2024-12-24 11:04 UTC by rameshkunasi

Added 16bit operator support for below operators:

1. unpack
2. transpose
3. comparison

2025-01-09 06:04 UTC, rameshkunasi commented on tensorflow/lite/micro/kernels/transpose.cc
> +          "Only float32, int8 and int16 is supported",
Updated

2025-01-09 06:04 UTC, rameshkunasi commented on tensorflow/lite/micro/kernels/fully_connected.cc
> +	  if (bias == nullptr || bias->type == kTfLiteInt32) {
Updated

2025-01-16 01:42 UTC, rameshkunasi commented
@gonnet can you please review

2025-01-27 10:23 UTC, gonnet approved these changes

2025-02-25 20:17 UTC, ddavis-2015 commented
@suleshahid No unit tests?

2025-03-13 18:15 UTC, ddavis-2015 requested changes

2025-03-14 03:58 UTC, rameshkunasi commented on tensorflow/lite/micro/kernels/fully_connected_test.cc
> +const int simple_bias_size = 3;
Updated

2025-03-14 03:58 UTC, rameshkunasi commented on tensorflow/lite/micro/kernels/fully_connected_test.cc
> +TF_LITE_MICRO_TEST(SimpleTestPerChannelQuantizedInt16) {
Updated

2025-03-14 06:24 UTC, ddavis-2015 requested changes

2025-03-14 06:24 UTC, ddavis-2015 commented on tensorflow/lite/micro/kernels/fully_connected_test.cc
> +#if !defined(XTENSA) && !defined(CMSIS_NN)
This is incorrect.  CMSIS_NN supports per channel quantization for INT8.

2025-03-14 18:19 UTC, rameshkunasi commented on tensorflow/lite/micro/kernels/fully_connected_test.cc
> +#if !defined(XTENSA) && !defined(CMSIS_NN)
updated the changes

2025-03-14 19:58 UTC, ddavis-2015 commented
@rameshkunasi I forgot to let you know that whenever a file is updated, its copyright date must also change.  Each changed file should have a current year copyright, and only a single year should appear in the copyright.  Do not reformat the copyright, as there is a CI check for its format.

2025-03-14 20:30 UTC, ddavis-2015 commented
@rameshkunasi `!defined(HEXAGON)` is needed around all per-channel quantized unit test code for FULLY_CONNECTED.

2025-03-15 03:56 UTC, rameshkunasi commented
> @rameshkunasi I forgot to let you know that whenever a file is updated, its copyright date must also change. Each changed file should have a current year copyright, and only a single year should appear in the copyright. Do not reformat the copyright, as there is a CI check for its format.

@ddavis-2015 Updated the changes as per your suggestions

2025-03-17 15:20 UTC, ddavis-2015 approved these changes
Looks good to me.  On to @suleshahid.

2025-03-17 16:44 UTC, merged