Fix misc formatting and spelling errors.
tensorflow/tflite-micro pull request #435
Opened 2021-08-18 01:02 UTC by njeffrie

Bug=196879878

2021-08-18 02:23 UTC, advaitjain approved these changes

2021-08-18 02:29 UTC, advaitjain requested changes
We want to continue to disable the layering check. That is the easiest way to ensure that external and internal errors are consistent.

See https://github.com/tensorflow/tflite-micro/pull/386#pullrequestreview-725882136 for additional context. 

I'm happy to switch to something else is we think that that would be preferred (including keeping the layering check and manually fix any errors when we import from github). Let me know what you think.

2021-08-19 06:38 UTC, njeffrie commented
Makes sense. I had removed due to warnings in the build, but I'll refrain from removing them now that I understand their purpose.

2021-08-19 06:42 UTC, advaitjain approved these changes

2021-08-19 17:18 UTC, advaitjain approved these changes

2021-08-19 17:53 UTC, advaitjain approved these changes

2021-08-19 17:53 UTC, merged